/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "M35PinpadApi.h"

//Defined in HXCardReader.m
extern void _Pinpad_Cancel(void);
extern int _Pinpad_Reset(int initFlag);
extern int _Pinpad_GetVersion(unsigned char *firmwareVersion, int *versionLength);
extern int _Pinpad_DownloadMasterKey(int is3des, int index, unsigned char * masterKey, int keyLength);
extern int _Pinpad_DownloadWorkingKey(int is3des, int masterIndex, int workingIndex, unsigned char* workingKey, int keyLength);
extern int _Pinpad_InputPinblock(int is3des, int isAutoReturn, int masterIndex, int workingIndex, char* cardNo, int pinLength, unsigned char *pinblock, int timeout);

extern int _Pinpad_InputPinblockWithAmount(int is3des, int isAutoReturn, int masterIndex, int workingIndex, int amount,char* cardNo, int pinLength, unsigned char *pinblock, int timeout);

extern int _Pinpad_Mac(int is3des, int masterIndex, int workingIndex, unsigned char* data, int dataLength, unsigned char *mac);

void M35Pinpad_Cancel(void)
{
    _Pinpad_Cancel();
}

int M35Pinpad_Reset(int initFlag)
{
    return _Pinpad_Reset(initFlag);
}

int M35Pinpad_GetVersion(unsigned char *firmwareVersion, int *versionLength)
{
    return _Pinpad_GetVersion(firmwareVersion, versionLength);
}

int M35Pinpad_DownloadMasterKey(int is3des, int index, unsigned char* masterKey, int keyLength)
{
    return _Pinpad_DownloadMasterKey(is3des, index, masterKey, keyLength);
}

int M35Pinpad_DownloadWorkingKey(int is3des, int masterIndex, int workingIndex, unsigned char* workingKey, int keyLength)
{
	return _Pinpad_DownloadWorkingKey(is3des, masterIndex, workingIndex, workingKey, keyLength);
}

int M35Pinpad_InputPinblock(int is3des, int isAutoReturn, int masterIndex, int workingIndex, char* cardNo, int pinLength, unsigned char *pinblock, int timeout)
{
    return _Pinpad_InputPinblock(is3des, isAutoReturn, masterIndex, workingIndex, cardNo, pinLength, pinblock, timeout);
}

int M35Pinpad_InputPinblockWithAmount(int is3des, int isAutoReturn, int masterIndex, int workingIndex, int amount,char* cardNo, int pinLength, unsigned char *pinblock, int timeout)
{
    return _Pinpad_InputPinblockWithAmount(is3des, isAutoReturn, masterIndex, workingIndex, amount, cardNo, pinLength, pinblock, timeout);
}

// Pinpad加解密数据
// in  : is3des  		: M35 无效，给false即可
//		 algo			: 算法，取值: ALGO_ENCRYPT 以ECB方式进行加密运算
//		 masterIndex	: M35 无效，给0即可
//	     workingIndex	: M35 无效，给0即可
//		 inData			: 加解密输入数据
//		 dataLength		: indata数据长度，必须为8的倍数
// out : outData		: 加解密输出的结果
// ret : 0				: 成功
//		 其它			: 失败
int M35Pinpad_Encrypt(int is3des, int algo, int masterIndex, int workingIndex, unsigned char *inData, int dataLength, unsigned char *outData)
{
    if ((dataLength % 8) != 0 )
        return 104;
    
    int ret;
    for(int i = 0; i < dataLength/8 ; i++ )
    {
        unsigned char mac[8];
        unsigned char datain[8];
        memcpy(datain, inData+8*i, 8);
        ret = _Pinpad_Mac(is3des, masterIndex, workingIndex, datain, 8, mac);
        if(ret!=0)
            return ret;
        memcpy(outData+i*8, mac, 8);
    }
    return 0;
}

int M35Pinpad_Mac(int is3des, int masterIndex, int workingIndex, unsigned char* data, int dataLength, unsigned char *mac)
{
    return _Pinpad_Mac(is3des, masterIndex, workingIndex, data, dataLength, mac);
}

